# Generated by Django 5.2.8 on 2025-11-12 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_data',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
