# Generated by Django 5.2.8 on 2025-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_address_order_full_name_order_note_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='snapshots',
            field=models.ManyToManyField(blank=True, to='shop.orderitemsnapshot'),
        ),
    ]
