# Generated by Django 5.2.8 on 2025-11-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
