# Generated by Django 5.2.8 on 2025-11-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_options_customuser_village_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='house',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='street',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='village',
        ),
    ]
